config/routes.rb
SaveThePrincess::Application.routes.draw do
  resources :characters
  
  resources :teams

end

app/models/barbarian.rb
# app/models/barbarian.rb
class Barbarian < Character
	# Extra attribute of barbarian to the character
	def attack()
		super + 1
	end

	def defend()
		super + 2
	end
end

app/models/battle.rb
# app/models/battle.rb
class Battle
	attr_accessor :challenger, :opponent

	# Store the fighters
	def initialize(params = {})
		@challenger = params[:challenger]
		@opponent = params[:opponent]
	end

	# Initiative
	def start
		recover_health_points_for challenger
		recover_health_points_for opponent

		first, last = initiative

		while (@challenger.alive?) && (@opponent.alive?)
			Round.new(challenger: first, opponent: last).start
		end
		
		@challenger.knocked_out? ? @opponent : @challenger
	end

	def recover_health_points_for(character)
		character.current_hp = character.health_points		
	end

	def initiative
		if Die.roll > Die.roll
			[challenger, opponent]
		else
			[opponent, challenger]
		end
	end
end

app/models/character.rb
# app/models/character.rb
require "die.rb"

class Character < ActiveRecord::Base
  attr_accessible :armor, :fire_power, :health_points, :name, :resistance, :skill, :strength
  belongs_to :team
  before_create :calculate_health_points
  after_initialize :default_values
  validates :name, presence: true
  validates :armor, numericality: { less_than_or_equal_to: 5 }, on: :create
  validates :fire_power, numericality: { less_than_or_equal_to: 5 }, on: :create
  validates :resistance, numericality: { less_than_or_equal_to: 5 }, on: :create
  validates :skill, numericality: { less_than_or_equal_to: 5 }, on: :create
  validates :strength, numericality: { less_than_or_equal_to: 5 }, on: :create
  validates :points_spent, numericality: { less_than_or_equal_to: 7 }, on: :create

  # Calculate attack for strength
  def attack
  	Die.roll(times: strength)
  end

  def defend
  	Die.roll(times: armor)
  end

  def calculate_health_points
  	if resistance == 0
  		self.health_points = 1
  	else
  		self.health_points = Die.roll(times: resistance)
  	end
  end

  def default_values
  	self.armor = 0 if armor.nil?
  	self.fire_power = 0 if fire_power.nil?
  	self.resistance = 0 if resistance.nil?
  	self.skill = 0 if skill.nil?
  	self.strength = 0 if strength.nil?
  end

  def points_spent
  	armor.to_i + fire_power.to_i + resistance.to_i + skill.to_i + strength.to_i
  end
end

app/models/dungeon.rb
# app/models/dungeon.rb
class Dungeon < ActiveRecord::Base
  attr_accessible :name
  attr_accessible :kind
  has_many :dungeon_teams
  has_many :teams, through: :dungeon_teams
end

app/models/dungeon_team.rb
# app/models/dungeon_team.rb
class DungeonTeam < ActiveRecord::Base
	belongs_to :dungeon
	belongs_to :team
end

app/models/mage.rb
# app/models/mage.rb
class Mage < Character
	# Extra attribute of mage to the character
	def protego()
		defend() + 2
	end
end

app/models/round.rb
# app/models/round.rb
class Battle::Round
	attr_accessor :challenger, :opponent

	# Store the fighters
	def initialize(params = {})
		@challenger = params[:challenger]
		@opponent = params[:opponent]

		self
	end

	def start
		Turn.new(attacker: @challenger, defender: @opponent).start
		if @opponent.current_hp > 0
			Turn.new(attacker: @opponent, defender: @challenger).start
		end
	end
end

app/models/team.rb
# app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name
  attr_accessible :character_ids
  has_many :characters
  has_many :dungeon_teams
  has_many :dungeons, through: :dungeon_teams
end

app/models/turn.rb
# app/models/turn.rb
class Battle::Round::Turn
	attr_accessor :attacker, :defender

	# Store the fighters
	def initialize(params = {})
		@attacker = params[:attacker]
		@defender = params[:defender]

		self
	end

	# Calculate damage
	def start
		puts "#{@attacker.name} was here!"
		damage = @attacker.attack - @defender.defend
		if damage > 0
			puts "#{@attacker.name} caused #{damage} damage to #{@defender.name}"
			@defender.current_hp -= damage
		else
			puts "#{@attacker.name} not caused damage to #{@defender.name}"
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @characters }
    end
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    @character = Character.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/new
  # GET /characters/new.json
  def new
    @character = Character.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/1/edit
  def edit
    @character = Character.find(params[:id])
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(params[:character])

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render json: @character, status: :created, location: @character }
      else
        format.html { render action: "new" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /characters/1
  # PUT /characters/1.json
  def update
    @character = Character.find(params[:id])

    respond_to do |format|
      if @character.update_attributes(params[:character])
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
	
	def index
		@teams = Team.all
	end

	def show
		@team = Team.find(params[:id])
	end

	def new
		@team = Team.new
	end

	def edit
		@team = Team.find(params[:id])
	end

	def create
		@team = Team.new(params[:team])

		if @team.save
			redirect_to @team, notice: 'Team was successfully created.'
		else
			render action: "new"
		end
	end

	def update
		@team = Team.find(params[:id])

		if @team.update_attributes(params[:team])
			redirect_to @team, notice: 'Team was successfully updated.'
		else
			render action: "edit"
		end
	end

	def destroy
		@team = Team.find(params[:id])
		@team.destroy

		redirect_to teams_url
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :strength %><br />
    <%= f.number_field :strength %>
  </div>
  <div class="field">
    <%= f.label :skill %><br />
    <%= f.number_field :skill %>
  </div>
  <div class="field">
    <%= f.label :resistance %><br />
    <%= f.number_field :resistance %>
  </div>
  <div class="field">
    <%= f.label :armor %><br />
    <%= f.number_field :armor %>
  </div>
  <div class="field">
    <%= f.label :fire_power %><br />
    <%= f.number_field :fire_power %>
  </div>
  <div class="field">
    <%= f.label :health_points %><br />
    <%= f.number_field :health_points %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Strength</th>
    <th>Skill</th>
    <th>Resistance</th>
    <th>Armor</th>
    <th>Fire power</th>
    <th>Health points</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @characters.each do |character| %>
  <tr>
    <td><%= character.name %></td>
    <td><%= character.strength %></td>
    <td><%= character.skill %></td>
    <td><%= character.resistance %></td>
    <td><%= character.armor %></td>
    <td><%= character.fire_power %></td>
    <td><%= character.health_points %></td>
    <td><%= link_to 'Show', character %></td>
    <td><%= link_to 'Edit', edit_character_path(character) %></td>
    <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @character.name %>
</p>

<p>
  <b>Strength:</b>
  <%= @character.strength %>
</p>

<p>
  <b>Skill:</b>
  <%= @character.skill %>
</p>

<p>
  <b>Resistance:</b>
  <%= @character.resistance %>
</p>

<p>
  <b>Armor:</b>
  <%= @character.armor %>
</p>

<p>
  <b>Fire power:</b>
  <%= @character.fire_power %>
</p>

<p>
  <b>Health points:</b>
  <%= @character.health_points %>
</p>


<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SaveThePrincess</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>